basePath: /_caltoph/v1
info:
  contact: {}
  title: Caltoph API
  version: "1.0"
paths:
  /health:
    get:
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Get app health
swagger: "2.0"
